name: EXAMPLE
recipe: wordpress
proxy:                
  appserver_nginx:
    - EXAMPLE.local
config:
  php: '8.0'
  via: nginx
  webroot: public_html
  xdebug: false
services:
  database:
    type: mariadb
    portforward: 3306
