name: EXAMPLE
recipe: wordpress
proxy:                
  appserver:
    - EXAMPLE.local
config:
  php: '8.1'
  via: apache
  webroot: public_html
  xdebug: false
services:
  database:
    type: mariadb
    portforward: 3306
keys:
  - id_rsa

